[project]
name = "task3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphic>=1.0.0a6",
    "graphics-py>=5.0.1.post1",
    "pygame>=2.6.1",
    "tk>=0.1.0",
]
